/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  AdvancedSearchbar as AdvancedSearchbar
} from './components/searchbar/searchbar';

declare global {
  interface HTMLAdvancedSearchbarElement extends AdvancedSearchbar, HTMLStencilElement {
  }
  var HTMLAdvancedSearchbarElement: {
    prototype: HTMLAdvancedSearchbarElement;
    new (): HTMLAdvancedSearchbarElement;
  };
  interface HTMLElementTagNameMap {
    "advanced-searchbar": HTMLAdvancedSearchbarElement;
  }
  interface ElementTagNameMap {
    "advanced-searchbar": HTMLAdvancedSearchbarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "advanced-searchbar": JSXElements.AdvancedSearchbarAttributes;
    }
  }
  namespace JSXElements {
    export interface AdvancedSearchbarAttributes extends HTMLAttributes {
      data?: any;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
